# Copyright (c) 2022 Dane Freeman.
# Distributed under the terms of the Modified BSD License.

channels:
  - conda-forge
  - nodefaults
dependencies:
  - anaconda-project
  - doit
  - python >=3.7,<3.10
