# Copyright (c) 2022 Dane Freeman.
# Distributed under the terms of the Modified BSD License.

name: jupyterlab-graph-lsp

channels:
- conda-forge
- nodefaults

dependencies:
- anaconda-project
- doit
- gql
- ipywidgets >=7.5.1,<8
- jupyter-lsp-python-plugins
- jupyterlab-lsp >=3.5,<4
- nodejs >=14,!=15.*,<17
- oxrdflib
- pyshacl
- rdflib >=6,<7
- reasonable
