#!/usr/bin/env bash

# Copyright (c) 2022 Dane Freeman.
# Distributed under the terms of the Modified BSD License.
set -eux

jlpm bootstrap
python3 -m pip install -e . --no-deps --ignore-installed
jupyter labextension develop . --overwrite
jupyter labextension list
