#!/usr/bin/env bash

# Copyright (c) 2022 Dane Freeman.
# Distributed under the terms of the Modified BSD License.
set -eux

doit -n8 build || doit build

python3 -m pip install -vv -e . --no-deps --ignore-installed

jupyter labextension develop . --overwrite

jupyter labextension list

cp .binder/jupyter_config.json .
